apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: example
  labels:
    app: example
webhooks:
  - name: mutateme.default.svc.cluster.local
    sideEffects: None
    admissionReviewVersions: ["v1"]
    clientConfig:
      caBundle: dGVzdAo=
      service:
        name: mutateme
        namespace: default
        path: "/mutate"
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchLabels:
        mutateme: enabled