apiVersion: v1
kind: Pod
metadata:
  labels:
    app: example
  name: example
  namespace: default
spec:
  containers:
  - image: registry.k8s.io/nginx-slim:0.8
    imagePullPolicy: IfNotPresent
    name: nginx
    resources: {}