apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: example
  labels:
    name: example
webhooks:
  - name: validateme.default.svc.cluster.local
    sideEffects: None
    admissionReviewVersions: ["v1"]
    clientConfig:
      caBundle: dGVzdAo=
      service:
        name: validateme
        namespace: default
        path: "/validate"
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchLabels:
        validateme: enabled